### ISSUE TITLE
Bug: Does not work when `ti` is only installed as part of `appc`

### ISSUE THREAD

**Issue by FokkeZB** [dbankier/timodules#5]
The new `appc` CLI has a local version of `ti` so a growing number of users won't have a global `ti` CLI anymore. The module could fall back to `appc ti`, but I saw that `appc ti module --output json` does not hide the AppC banner (I would say that's a bug) so it cannot be parsed as JSON (as-is).

**Comment by dbankier** [comment]
Is `appc` just a pass through? Why not expose it globally?
Will wait on the bug to be fixed.

**Comment by FokkeZB** [comment]
It's not a pass through to the global CLI's but bundles local versions of the `ti`, `alloy` and `acs` CLI. And if one installs just `appcelerator` and not `titanium` they will not have `ti` but only `appc`.

So the module should test if `ti` is there and if not fall back to `appc ti`.

I'll create a ticket for the JSON.

**Comment by FokkeZB** [comment]
The workaround is to use:

```
appc ti module -o json --no-banner
```

**Comment by FokkeZB** [comment]
Related ticket: https://jira.appcelerator.org/browse/CLI-622

**Comment by FokkeZB** [comment]
@dbankier, try http://npmjs.com/package/appc-compat

**Comment by dbankier** [comment]
PR? :)
